[workspace]
authors = ["dasha <daria.carlberg@gmail.com>"]
channels = ["conda-forge"]
name = "CI_test"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks.generate-schema]
cmd = "python model.py > text.schema.json"

[tasks.tomarkdown]
cmd = "jsonschema2md text.schema.json docs/index.md"

[tasks.build-mkdocs]
cmd = "mkdocs build"

[dependencies]
python = ">=3.10"
pip = "*"
nodejs = ">=22.13.0,<22.14"
pydantic = ">=2.11.3,<3"
jsonschema2md = ">=1.3.0,<2"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.12,<10"
