name: test 

on: push

jobs:
  automation_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Pixi
        run: curl -sSf https://pixi.sh/install.sh | bash

      - name: Install project environment
        run: pixi install

      - name: generate_json
        run: pixi run generate-schema #run generate schema from model.py > schema.json

      - name: generate_md #run schema.json > index.md
        run: pixi run tomarkdown 

      - name: build_mkdocs
        run: pixi run build-mkdocs #pixi builds the mkdocs site
  
      - name: deploy_github_pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
