name: test 

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@main
        with:
          cache: true

      - name: Install environment
        run: pixi install

      - name: Generate schema
        run: pixi run generate-schema

      - name: Generate Markdown
        run: pixi run tomarkdown

      - name: Build MkDocs site
        run: pixi run build-mkdocs
